account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('form/', views.account_view, name="form"),
    path('delete/<str:pk>/', views.delete, name="delete")
]

studentprofile/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('students.urls')),
    path('account/', include('account.urls'))
]

students/urls.py
from django.urls import path
from . import views

app_name = 'students'
urlpatterns = [
    path('', views.index, name="index")
]

account/models.py
from django.db import models
from datetime import timezone
# Create your models here.

class StudentAccount(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.CharField(max_length=200)
    date_created = models.DateTimeField(auto_now=timezone)

    def __str__(self):
        return self.name

students/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from .models import StudentAccount

class StudentForm(forms.ModelForm):

    class Meta:
        model = StudentAccount
        fields = ['name', 'email', 'phone']

account/views.py
from django.shortcuts import render, redirect
from .forms import StudentForm
from .models import StudentAccount

# Create your views here.
def account_view(request):
    form = StudentForm()
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        
        user = StudentAccount(name=name, email=email, phone=phone)
        user.save()
        return redirect('/')
    else:
     return render(request, 'account/form.html', {'form': form})


def delete(request, pk):
    student = StudentAccount.objects.get(id=pk)
    student.delete()
    return redirect('/')

students/views.py
from django.shortcuts import render
from account.models import StudentAccount


# Create your views here.
def index(request):
    students = StudentAccount.objects.all()
    return render(request, 'students/index.html',{'students': students})

templates/students/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    {%block content%}
    
    {% endblock%}
</body>
</html>

templates/students/index.html
{% extends 'students/base.html'%}

{% block title %} Home Page {% endblock %}

{% block content %} 
    <h1>Welcome To Student Profile App.</h1>
    <h2><a href="{% url 'account:form' %}">Add Student</a></h2>
    {% if students %}
        <table>
            <thead>
                <tr>
                    <th>Student ID</th>
                    <th>Full Name</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Edit Profile</th>
                    <th>Delete Profile</th>
                </tr>
            </thead>
            <tbody>
            
                    {% for student in students %}
                        <tr>
                            <td>{{ student.id }}</td>
                            <td>{{student.name}}</td>
                            <td>{{student.email}}</td>
                            <td>{{student.phone}}</td>
                            <td>
                                <form action="{% url 'account:delete' student.id %}" method="POST">
                                    {% csrf_token %}
                                    <input type="submit" value="Delete">
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
            
            </tbody>
        </table>
    {% endif %}
{% endblock %}